name = "Duo Pack"
author = "Fniges, 8ballpizza"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e2325d2b5d3bcfc0698a4f4365bc99f25f46a48541e9d3cec3739676b364038"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
