name = "Duo Pack"
author = "Fniges, 8ballpizza"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faea039d7c63e7fe015441b247c05af9029011255bf7eb468503f8576c430706"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
