name = "Duo Pack"
author = "Fniges, 8ballpizza"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1d564f434a65586e899a5dbe051ae3bc593dccf80cdbb827f7ceaeee8e6354e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
