# i dont want our work to disappear
obsidianBlocks = [
   "minecraft:obsidian",
   "minecraft:crying_obsidian",
   "minecraft:respawn_anchor",
   "regions_unexplored:cobalt_obsidian",
   "chipped:massive_obsidian_bricks",
   "chipped:simple_obsidian_pillar",
   "chipped:ornate_obsidian_pillar",
   "chipped:fine_obsidian_pillar",
   "chipped:curly_obsidian_pillar",
   "chipped:tiny_brick_bordered_obsidian",
   "chipped:tiled_bordered_obsidian",
   "chipped:tiled_obsidian_column",
   "chipped:thick_inlayed_obsidian",
   "chipped:smooth_obsidian_column",
   "chipped:polished_obsidian",
   "chipped:overlapping_obsidian_tiles",
   "chipped:edged_obsidian_bricks",
   "chipped:cut_obsidian_column",
   "chipped:brick_bordered_obsidian",
   "chipped:bordered_obsidian",
   "chipped:weathered_obsidian",
   "chipped:vertical_disordered_obsidian_bricks",
   "chipped:vertical_cut_obsidian",
   "chipped:unamused_obsidian",
   "chipped:trodden_obsidian",
   "chipped:tiny_layered_obsidian_slabs",
   "chipped:tiny_layered_obsidian_bricks",
   "chipped:tiny_obsidian_bricks",
   "chipped:tiled_obsidian",
   "chipped:stacked_obsidian_bricks",
   "chipped:spiraled_obsidian",
   "chipped:spider_obsidian_carving",
   "chipped:smoothed_double_inlayed_obsidian",
   "chipped:smooth_ringed_obsidian",
   "chipped:smooth_inlayed_obsidian",
   "chipped:small_obsidian_bricks",
   "chipped:sanded_obsidian",
   "chipped:sad_obsidian",
   "chipped:runic_carved_obsidian",
   "chipped:rounded_obsidian_bricks",
   "chipped:rough_obsidian",
   "chipped:prismal_obsidian_remnants",
   "chipped:pillar_obsidian_bricks",
   "chipped:offset_obsidian_bricks",
   "chipped:loded_obsidian",
   "chipped:layed_obsidian_bricks",
   "chipped:inscribed_obsidian",
   "chipped:inlayed_obsidian",
   "chipped:flat_obsidian_tiles",
   "chipped:etched_obsidian_bricks",
   "chipped:eroded_obsidian",
   "chipped:engraved_obsidian",
   "chipped:duh_obsidian",
   "chipped:glad_obsidian",
   "chipped:cut_blank_obsidian",
   "chipped:crying_obsidian",
   "chipped:creeper_obsidian_carving",
   "chipped:cracked_flat_obsidian_tiles",
   "chipped:cracked_disordered_obsidian_bricks",
   "chipped:cracked_obsidian_bricks",
   "chipped:cobbled_obsidian",
   "chipped:checkered_obsidian_tiles",
   "chipped:carved_obsidian",
   "chipped:blank_obsidian_carving",
   "chipped:angry_obsidian",
   "chipped:obsidian_scales",
   "chipped:obsidian_pillar_top",
   "chipped:obsidian_pillar",
   "chipped:obsidian_mini_tiles",
   "chipped:obsidian_bricks",
   "chipped:massive_crying_obsidian_bricks",
   "chipped:simple_crying_obsidian_pillar",
   "chipped:ornate_crying_obsidian_pillar",
   "chipped:fine_crying_obsidian_pillar",
   "chipped:curly_crying_obsidian_pillar",
   "chipped:tiny_brick_bordered_crying_obsidian",
   "chipped:tiled_bordered_crying_obsidian",
   "chipped:tiled_crying_obsidian_column",
   "chipped:thick_inlayed_crying_obsidian",
   "chipped:smooth_crying_obsidian_column",
   "chipped:polished_crying_obsidian",
   "chipped:overlapping_crying_obsidian_tiles",
   "chipped:edged_crying_obsidian_bricks",
   "chipped:cut_crying_obsidian_column",
   "chipped:brick_bordered_crying_obsidian",
   "chipped:bordered_crying_obsidian",
   "chipped:weathered_crying_obsidian",
   "chipped:vertical_disordered_crying_obsidian_bricks",
   "chipped:vertical_cut_crying_obsidian",
   "chipped:unamused_crying_obsidian",
   "chipped:trodden_crying_obsidian",
   "chipped:tiny_layered_crying_obsidian_slabs",
   "chipped:tiny_layered_crying_obsidian_bricks",
   "chipped:tiny_crying_obsidian_bricks",
   "chipped:tiled_crying_obsidian",
   "chipped:stacked_crying_obsidian_bricks",
   "chipped:spiraled_crying_obsidian",
   "chipped:spider_crying_obsidian_carving",
   "chipped:smoothed_double_inlayed_crying_obsidian",
   "chipped:smooth_ringed_crying_obsidian",
   "chipped:smooth_inlayed_crying_obsidian",
   "chipped:small_crying_obsidian_bricks",
   "chipped:sanded_crying_obsidian",
   "chipped:sad_crying_obsidian",
   "chipped:runic_carved_crying_obsidian",
   "chipped:rounded_crying_obsidian_bricks",
   "chipped:rough_crying_obsidian",
   "chipped:prismal_crying_obsidian_remnants",
   "chipped:pillar_crying_obsidian_bricks",
   "chipped:offset_crying_obsidian_bricks",
   "chipped:loded_crying_obsidian",
   "chipped:layed_crying_obsidian_bricks",
   "chipped:inscribed_crying_obsidian",
   "chipped:inlayed_crying_obsidian",
   "chipped:flat_crying_obsidian_tiles",
   "chipped:etched_crying_obsidian_bricks",
   "chipped:eroded_crying_obsidian",
   "chipped:engraved_crying_obsidian",
   "chipped:duh_crying_obsidian",
   "chipped:glad_crying_obsidian",
   "chipped:cut_blank_crying_obsidian",
   "chipped:crying_crying_obsidian",
   "chipped:creeper_crying_obsidian_carving",
   "chipped:cracked_flat_crying_obsidian_tiles",
   "chipped:cracked_disordered_crying_obsidian_bricks",
   "chipped:cracked_crying_obsidian_bricks",
   "chipped:cobbled_crying_obsidian",
   "chipped:checkered_crying_obsidian_tiles",
   "chipped:carved_crying_obsidian",
   "chipped:blank_crying_obsidian_carving",
   "chipped:angry_crying_obsidian",
   "chipped:crying_obsidian_scales",
   "chipped:crying_obsidian_pillar_top",
   "chipped:crying_obsidian_pillar",
   "chipped:crying_obsidian_mini_tiles",
   "chipped:crying_obsidian_bricks",
   "quark:obsidian_pressure_plate",
   "rechiseled:obsidian_bordered",
   "rechiseled:obsidian_bordered_connecting",
   "rechiseled:obsidian_bordered_stairs",
   "rechiseled:obsidian_bordered_stairs_connecting",
   "rechiseled:obsidian_bordered_slab",
   "rechiseled:obsidian_bordered_slab_connecting",
   "rechiseled:obsidian_brick_pattern",
   "rechiseled:obsidian_brick_pattern_connecting",
   "rechiseled:obsidian_brick_pattern_stairs",
   "rechiseled:obsidian_brick_pattern_stairs_connecting",
   "rechiseled:obsidian_brick_pattern_slab",
   "rechiseled:obsidian_brick_pattern_slab_connecting",
   "rechiseled:obsidian_brick_paving",
   "rechiseled:obsidian_brick_paving_connecting",
   "rechiseled:obsidian_brick_paving_stairs",
   "rechiseled:obsidian_brick_paving_stairs_connecting",
   "rechiseled:obsidian_brick_paving_slab",
   "rechiseled:obsidian_brick_paving_slab_connecting",
   "rechiseled:obsidian_bricks",
   "rechiseled:obsidian_bricks_connecting",
   "rechiseled:obsidian_bricks_stairs",
   "rechiseled:obsidian_bricks_stairs_connecting",
   "rechiseled:obsidian_bricks_slab",
   "rechiseled:obsidian_bricks_slab_connecting",
   "rechiseled:obsidian_chiseled",
   "rechiseled:obsidian_chiseled_connecting",
   "rechiseled:obsidian_chiseled_stairs",
   "rechiseled:obsidian_chiseled_stairs_connecting",
   "rechiseled:obsidian_chiseled_slab",
   "rechiseled:obsidian_chiseled_slab_connecting",
   "rechiseled:obsidian_chiseled_circles",
   "rechiseled:obsidian_chiseled_circles_connecting",
   "rechiseled:obsidian_chiseled_circles_stairs",
   "rechiseled:obsidian_chiseled_circles_stairs_connecting",
   "rechiseled:obsidian_chiseled_circles_slab",
   "rechiseled:obsidian_chiseled_circles_slab_connecting",
   "rechiseled:obsidian_chiseled_creeper",
   "rechiseled:obsidian_chiseled_creeper_stairs",
   "rechiseled:obsidian_chiseled_creeper_slab",
   "rechiseled:obsidian_chiseled_skeleton",
   "rechiseled:obsidian_chiseled_skeleton_stairs",
   "rechiseled:obsidian_chiseled_skeleton_slab",
   "rechiseled:obsidian_dark",
   "rechiseled:obsidian_dark_connecting",
   "rechiseled:obsidian_dark_stairs",
   "rechiseled:obsidian_dark_stairs_connecting",
   "rechiseled:obsidian_dark_slab",
   "rechiseled:obsidian_dark_slab_connecting",
   "rechiseled:obsidian_large_tiles",
   "rechiseled:obsidian_large_tiles_stairs",
   "rechiseled:obsidian_large_tiles_slab",
   "rechiseled:obsidian_pillars",
   "rechiseled:obsidian_pillars_connecting",
   "rechiseled:obsidian_pillars_stairs",
   "rechiseled:obsidian_pillars_stairs_connecting",
   "rechiseled:obsidian_pillars_slab",
   "rechiseled:obsidian_pillars_slab_connecting",
   "rechiseled:obsidian_rotated_bricks",
   "rechiseled:obsidian_rotated_bricks_connecting",
   "rechiseled:obsidian_rotated_bricks_stairs",
   "rechiseled:obsidian_rotated_bricks_stairs_connecting",
   "rechiseled:obsidian_rotated_bricks_slab",
   "rechiseled:obsidian_rotated_bricks_slab_connecting",
   "rechiseled:obsidian_spots",
   "rechiseled:obsidian_spots_connecting",
   "rechiseled:obsidian_spots_stairs",
   "rechiseled:obsidian_spots_stairs_connecting",
   "rechiseled:obsidian_spots_slab",
   "rechiseled:obsidian_spots_slab_connecting",
   "rechiseled:obsidian_squares",
   "rechiseled:obsidian_squares_connecting",
   "rechiseled:obsidian_squares_stairs",
   "rechiseled:obsidian_squares_stairs_connecting",
   "rechiseled:obsidian_squares_slab",
   "rechiseled:obsidian_squares_slab_connecting",
   "rechiseled:obsidian_stripes",
   "rechiseled:obsidian_stripes_connecting",
   "rechiseled:obsidian_stripes_stairs",
   "rechiseled:obsidian_stripes_stairs_connecting",
   "rechiseled:obsidian_stripes_slab",
   "rechiseled:obsidian_stripes_slab_connecting",
   "rechiseled:obsidian_tiles",
   "rechiseled:obsidian_tiles_connecting",
   "rechiseled:obsidian_tiles_stairs",
   "rechiseled:obsidian_tiles_stairs_connecting",
   "rechiseled:obsidian_tiles_slab",
   "rechiseled:obsidian_tiles_slab_connecting"
]